spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mall
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

kafka:
  bootstrap-servers: localhost:9092
  topic:
    notification: notification-topic

email:
  from: no-reply@mall.com
  host: smtp.your-email-provider.com
  port: 587
  username: your_email_username
  password: your_email_password
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

push:
  service-url: http://push-notification-service:8084/api/push
  api-key: your_push_service_api_key

logging:
  level:
    org.springframework: INFO
    com.example.notificationservice: DEBUG